export const SCLUB_MEMBER_KEYS = {
    PROFILE_PICTURE: 'profilePicture',
    FILE: 'file',
    GENDER: 'gender',
    IMAGE_URL: 'imageURL',
    EMAIL: 'email',
    PASSWORD: 'password',
    CONFIRM_PASSWORD: 'confirmPassword',
    FULL_NAME: 'fullName',
    PHONE: 'phone',
    DIAL_CODE: 'dialCode',
    PHONE_NUMBER: 'phoneNumber',
    BIRTHDAY: 'birthday',
    ADDRESS: 'address',
    UNIVERSITY: 'university',
    MAJOR: 'major',
    MEMBER_TYPE: 'memberType',
    HOUSE: 'house',
    HAS_ROLE: 'hasRole',
    PARTICIPANT_TERM: 'participantTerm',
    TERM: 'term',
    ROLE: 'role',
    ROLES: 'roles',
} as const
