export const SCLUB_MEMBER_KEYS = {
  EMAIL: 'email',
  PASSWORD: 'password',
  CONFIRM_PASSWORD: 'confirmPassword',
  FULL_NAME: 'fullName',
  PHONE: 'phone',
  DIAL_CODE: 'dialCode',
  PHOME_NUMBER: 'phoneNumber',
  BIRTHDAY: 'birthday',
  ADDRESS: 'address',
  UNIVERSITY: 'university',
  MAJOR: 'major',
  MEMBER_TYPE: 'memberType',
  HOUSE: 'house',
  HASROLE: 'hasRole',
  PARTICIPANT_TERM: 'participantTerm',
  TERM: 'term',
  ROLE: 'role',
  ROLES: 'roles',
} as const
