export const WINDOW_WIDTH = {
  SMALL: 640,
  MEDIUM: 768,
  LARGE: 1024,
  EXTRA_LARGE: 1280,
  DOUBLE_EXTRA_LARGE: 1536,
}

export const WINDOW_SCALE = {
  SMALL: 'SMALL',
  MEDIUM: 'MEDIUM',
  LARGE: 'LARGE',
  EXTRA_LARGE: 'EXTRA_LARGE',
  DOUBLE_EXTRA_LARGE: 'DOUBLE_EXTRA_LARGE',
}
