export const DATE_FORMAT = {
    'MM/DD/YYYY': 'MM/DD/YYYY',
    'DD/MM/YY': 'DD/MM/YY',
    'YY/MM/DD': 'YY/MM/DD',
    'YYYY/MM/DD': 'YYYY/MM/DD',
    'Month D, Yr': 'Month D, Yr',
    'M/D/YY': 'M/D/YY',
    'D/M/YY': 'D/M/YY',
    'YY/M/D': 'YY/M/D',
    'bM/bD/YY': 'bM/bD/YY',
    'bD/bM/YY': 'bD/bM/YY',
    'YY/bM/bD': 'YY/bM/bD',
    'MMDDYY': 'MMDDYY',
    'DDMMYY': 'DDMMYY',
    'YYMMDD': 'YYMMDD',
    'MonDDYY': 'MonDDYY',
    'DDMonYY': 'DDMonYY',
    'YYMonDD': 'YYMonDD',
    'day/YY': 'day/YY',
    'YY/day': 'YY/day',
    'D Month, Yr': 'D Month, Yr',
    'Yr, Month D': 'Yr, Month D',
    'Mon-DD-YYYY': 'Mon-DD-YYYY',
    'DD-Mon-YYYY': 'DD-Mon-YYYY',
    'YYYYY-Mon-DD': 'YYYYY-Mon-DD',
    'Mon DD, YYYY': 'Mon DD, YYYY',
    'DD Mon, YYYY': 'DD Mon, YYYY',
    'YYYY, Mon DD': 'YYYY, Mon DD',
}
